### ISSUE TITLE
Component: Input Field

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#14]
### Description
The Input Field component is very basic now. We need this component to be more robust, adding invalid mode styles, error messages and disable mode styles. Add a prop to render an Icon at the beginning or the end of the input field and if input type is password add a button to reveal the text.

### Tasks
- [x] Create Invalid Mode with error message.
- [x] Create Disable mode.
- [x] Create Password type support.
- [x] Add placeholder support leaving the label outside if placeholder has any value.
