### ISSUE TITLE
Auth: SSO with Facebook

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#16]
### Description
Add support to SSO with Facebook

### Tasks
- [ ] Configure supabase to support sso with facebook
- [ ] Add Login button with Facebook to login form
- [ ] create story of the button

### How to test
Test on storybook
