### ISSUE TITLE
Auth: SSO with Google

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#17]
### Description
Add support to SSO with Google

### Tasks
- [ ] Configure Supabase to support SSO with Google
- [ ] Add "Login button with Google" to login form
- [ ] create story of the button

### How to test
Test on storybook
