### ISSUE TITLE
Feature: Auth: Sign Up

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#31]
### Description
Users need to sign up to the app to start using it. In the route /auth/signup create the form to take care of. 
Sign-up form  will be with email and password, add an extra confirm password to validate in the client side that the user entered the same password and didn't commit any mistake. 

### Tasks
- [x] Create signup form.
- [x] Create server action.
- [x] Create confirmation page.
