### ISSUE TITLE
Feature: Auth: Logout

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#33]
### Description
Add a way to log out from the app.

### Tasks
- [x] Create Avatar component and us it in the header
- [x] Create Menu component
- [x] Add Logout function to menu component
