### ISSUE TITLE
Feature: Dashboard: Search Groups

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#42]
### Description
Create Search groups page in /dashboard/groups list all the existing groups in the page in a list of 20 by 20. Add filter support by country, city
The search will filter the matching results by group name, city, country, owner.

### Tasks
- [x] Create Groups Page.
- [x] Add input search.
- [x] List groups.
- [ ] Add go back button.
- [ ] Add pagination.
- [ ] Add filter.

### How to test
Go to /dashboard/groups
