### ISSUE TITLE
Feature: Settings page

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#45]
### Description
User can change the settings of the app itself. Render a Shadui Sheet with the component to change language and the component to change the theme.

### Tasks
- [ ] install sheet from shadui.
- [ ] trigger it from settings.
- [ ] add language and theme components
