### ISSUE TITLE
Feature: User name

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot#49]
### Description
Ask for the user's name in signup form.

### Tasks
- [x] Ask for the user's name.
- [x] Set it in Supabase in the Auth schema and in the public schema.
- [x] Change Supabase trigger function to also set the users name.
- [x] render the user's name in the dashboard page

### How to test
in the /dashboard page name should be rendered.
